import sonarjs from 'eslint-plugin-sonarjs';
import globals from 'globals';

// Every src/*.js file is a classic <script defer>, loaded into one shared
// global scope (see CLAUDE.md — src/core.js first, src/platform.js last).
// These are declared cross-file so eslint doesn't flag legitimate
// cross-file reads/writes as no-undef.
const portbillSharedGlobals = {
  DEBUG: 'writable',
  dbg: 'readonly',
  calcVATmpa: 'readonly',
  calcSlabs: 'readonly',
  calcCarBillingSdSlabs: 'readonly',
  RATE_DEFAULTS: 'readonly',
  loadSavedRates: 'readonly',
  saveRates: 'readonly',
  resetRatesToDefaults: 'readonly',
  showToast: 'readonly',
  confirmModal: 'readonly',
  isValidDateStr: 'readonly',
  setFieldState: 'readonly',
  validateDateField: 'readonly',
  validateDateOrder: 'readonly',
  isAdmin: 'writable',
  _sessionWriteToken: 'writable',
  hashText: 'readonly',
  getAdminPasswordHash: 'readonly',
  AP_HASH: 'writable',
  loginAttempts: 'writable',
  _cloudPasswordHash: 'writable',
  _selectedRotation: 'writable',
  currentModule: 'writable',
  isInitialLoad: 'writable',
  lastCarBill: 'writable',
  lastCargoBill: 'writable',
  lastReexportBill: 'writable',
  editingBillNumber: 'writable',
  domCache: 'writable',
  initDomCache: 'readonly',
  partBillingStages: 'writable',
  reexportBEs: 'writable',
  escHtml: 'readonly',
  gn: 'readonly',
  gb: 'readonly',
  nn: 'readonly',
  saveBill: 'readonly',
  getSavedBills: 'readonly',
  persistSavedBill: 'readonly',
  ceilTon: 'readonly',
  collectCarErrors: 'readonly',
  collectCargoErrors: 'readonly',
  collectReexportErrors: 'readonly',
  reportInputErrors: 'readonly',
  PROXY_URL: 'readonly',
  switchModule: 'readonly',
  updateAdminNavigation: 'readonly',
  toggleAdmin: 'readonly',
  doLogin: 'readonly',
  changeAdminPassword: 'readonly',
  applyAdmin: 'readonly',
  carCompute: 'readonly',
  carCalculate: 'readonly',
  carRefresh: 'readonly',
  carRefreshNow: 'readonly',
  buildCarBillTable: 'readonly',
  loadRotations: 'readonly',
  addRotation: 'readonly',
  deleteRotation: 'readonly',
  renderRotationTable: 'readonly',
  refreshRotationInBill: 'readonly',
  saveRotationsToWorker: 'readonly',
  putHeaders: 'readonly',
  cargoCompute: 'readonly',
  cargoCalculate: 'readonly',
  cargoRefresh: 'readonly',
  cargoRefreshNow: 'readonly',
  computePartBillingWharfrent: 'readonly',
  pbMaxWeight: 'readonly',
  pbMaxSdWeight: 'readonly',
  pbBalanceChange: 'readonly',
  pbSdBalanceChange: 'readonly',
  cargoIncludeWharfrent: 'writable',
  cargoIncludePayables: 'writable',
  getCargoTierLabel: 'readonly',
  getReexportLandingRate: 'readonly',
  calcReexportWharfRent: 'readonly',
  reexportCompute: 'readonly',
  reexportCalculate: 'readonly',
  reexportRefresh: 'readonly',
  reexportRefreshNow: 'readonly',
  renderBillOfEntries: 'readonly',
  addBillOfEntry: 'readonly',
  removeBillOfEntry: 'readonly',
  addCld: 'readonly',
  removeCld: 'readonly',
  buildInvoiceHtml: 'readonly',
  openPrintPreview: 'readonly',
  printBill: 'readonly',
  saveBillsToWorker: 'readonly',
  saveConfigToWorker: 'readonly',
  loadConfigFromGitHub: 'readonly',
  loadBillsFromWorker: 'readonly',
  saveDraft: 'readonly',
  clearDraft: 'readonly',
  getDraft: 'readonly',
  restoreFormDraft: 'readonly',
  billInputSnapshot: 'readonly',
  hasMeaningfulDraft: 'readonly',
  getDeviceId: 'readonly',
  trackVisit: 'readonly',
  loadStats: 'readonly',
  renderStats: 'readonly',
  statsDayKey: 'readonly',
  renderSavedBills: 'readonly',
  editSavedBill: 'readonly',
  printSavedBill: 'readonly',
  deleteSavedBill: 'readonly',
  sbSearch: 'readonly',
  matchesBillSearch: 'readonly',
  buildRows: 'readonly',
  closeAdminPasswordPanel: 'readonly',
};

export default [
  {
    ignores: ['node_modules/**', '.wrangler/**'],
  },
  sonarjs.configs.recommended,
  {
    files: ['src/**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'script',
      globals: {
        ...globals.browser,
        ...portbillSharedGlobals,
      },
    },
  },
  {
    files: ['worker.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'module',
      globals: {
        ...globals.worker,
      },
    },
  },
  {
    files: ['sw.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'script',
      globals: {
        ...globals.serviceworker,
      },
    },
  },
  {
    files: ['tests/**/*.js'],
    languageOptions: {
      ecmaVersion: 'latest',
      sourceType: 'commonjs',
      globals: {
        ...globals.node,
      },
    },
    rules: {
      // vat.test.js is a custom console-based runner (no describe/it), so this
      // rule's whole-file check never sees a recognized test call. An inline
      // eslint-disable can't cover it since the rule reports at position 0:1,
      // before any comment in the file — must be turned off at config level.
      'sonarjs/no-empty-test-file': 'off',
    },
  },
];
